Issue 103: HouseController unit tests
jmprathab/MyHome pull request #139
Opened 2020-08-31 17:56 UTC by DDmit04

## 🚀 Description

add unit tests for `HouseController `

## 📄 Motivation and Context

Closes #103

2020-08-31 18:24 UTC, DDmit04 commented
srange,on my PC with IDEA tests are passed (`gradlew build` passed too)

2020-08-31 18:25 UTC, DDmit04 commented
For some reasons this lines fails test
```
verify(communityRepository).findByCommunityId(TEST_COMMUNITY_ID);
testCommunityHouses.forEach(house -> verify(communityHouseRepository).deleteByHouseId(house.getHouseId()));
```

2020-08-31 18:31 UTC, DDmit04 commented
is this necessary to use `@Transactional` on this methods?
```
@Transactional
  public boolean deleteCommunity(String communityId)
....
@Transactional
  public boolean removeHouseFromCommunityByHouseId(String communityId, String houseId)
```

2020-09-01 17:20 UTC, mslowiak requested changes

2020-09-01 17:20 UTC, mslowiak commented on src/main/java/com/myhome/controllers/HouseController.java
> +    return communityHouseOptional
Can we simplify this to:
```
return houseService.getHouseDetailsById(houseId)
   .map<rest of the code>
```

2020-09-01 17:20 UTC, mslowiak commented on src/main/java/com/myhome/controllers/HouseController.java
> +        .orElse(ResponseEntity.status(HttpStatus.NOT_FOUND).body(new GetHouseDetailsResponse()));
```
        .orElse(ResponseEntity.notFound().build());
```

2020-09-01 17:20 UTC, mslowiak commented on src/test/java/com/myhome/controllers/unit/HouseControllerTest.java
> +import static org.junit.jupiter.api.Assertions.*;
wildcard import

2020-09-01 17:20 UTC, mslowiak commented on src/test/java/com/myhome/controllers/unit/HouseControllerTest.java
> +  private Set<CommunityHouse> getTestHouses(int count) {
Please move helper methods to the bottom (tests first)

2020-09-01 17:20 UTC, mslowiak commented on src/test/java/com/myhome/services/unit/CommunitySDJpaServiceTest.java
> +    verify(communityRepository ,times(TEST_HOUSES_COUNT + 1)).findByCommunityId(TEST_COMMUNITY_ID);
Please apply the correct formatting

2020-09-01 20:23 UTC, mslowiak approved these changes

2020-09-02 12:22 UTC, merged