Issue #149 : Add current user as Admin when creating a community
jmprathab/MyHome pull request #154
Opened 2020-10-04 11:28 UTC by tomsajuk

## 🚀 Description

Adding the current user as Admin when creating a community. The userId is taken from the SecurityContextHolder.

## 📄 Motivation and Context

Change is required as there are no admins being assigned to a newly created community.
Fixes [Issue #149 ](https://github.com/jmprathab/MyHome/issues/149)

## 🧪 How Has This Been Tested?

Tested using Postman and Testcases.

## 📷 Screenshots (if appropriate)
NA

## 📦 Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [x] My code follows the code style of this project(Do your best to follow code styles. If none apply just skip this).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-10-04 17:02 UTC, mslowiak requested changes

2020-10-04 17:02 UTC, mslowiak commented on service/src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java
> +      admin.getCommunities().add(community);
Let's extract that action to a separate method please :)

2020-10-04 18:01 UTC, mslowiak commented
If you could also rename the commit message "Made changes to the test case" to "Issue 149: Made changes to the test case" I would be grateful. Thanks!

2020-10-05 03:13 UTC, tomsajuk commented
@mslowiak Made a fresh start with a single commit. Hope that's okay

2020-10-05 10:37 UTC, mslowiak approved these changes

2020-10-05 10:37 UTC, mslowiak commented
@tomsajuk great, thanks!

2020-10-05 10:38 UTC, merged