Issue #116: Delete Amenity Booking
jmprathab/MyHome pull request #179
Opened 2020-10-10 06:18 UTC by tomsajuk

## 🚀 Description

Added endpoint for deleting a booking by booking_id

## 📄 Motivation and Context

To delete a amenity booking

Closes #116 

## 🧪 How Has This Been Tested?

Tested via postman and unit testing

## 📦 Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [x] My code follows the code style of this project(Do your best to follow code styles. If none apply just skip this).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-10-10 06:29 UTC, tomsajuk commented
@mslowiak @jmprathab 
The end point is /booking/{booking_id} as I felt that for deleting a booking only booking id is required. Passing amenity id didn't feel right to me as its not used for deleting.

I changed mapping of AmenityBookingItem to Amenity and User to Many To One. Do suggest if that's okay.

2020-10-10 07:36 UTC, mslowiak commented
For me the issue is not clear at this point.
I don't know if the main goal of this issue is to delete a booking where amenityId belongs to or to delete amenity with id from booking where it exists.
@jmprathab you created that story, can you describe your point of view?

2020-10-11 07:20 UTC, jmprathab requested changes
@mslowiak 
The goal of this issue is to delete a booking.

@tomsajuk You are right. Amenity ID is not required for deleting a booking. Your approach is well and good.

2020-10-11 07:20 UTC, jmprathab commented on service/src/main/java/com/myhome/domain/AmenityBookingItem.java
>    @Column
This needs to be Non-Null as well

2020-10-14 15:46 UTC, jmprathab commented
@tomsajuk Please look into the following
- Fix conflict
- Please use assertive language in [commit](e9f57722546463f474868480ca119dbb7dfc3242) message
- Please follow the branch name convention as described in [CONTRIBUTING.md](github.com/jmprathab/MyHome/blob/master/CONTRIBUTING.md)

Once these are taken care this is ready to be merged.

2020-10-14 15:49 UTC, jmprathab requested changes
@tomsajuk Please look into the following
- Fix conflict
- Use assertive language in [commit](e9f57722546463f474868480ca119dbb7dfc3242) message
- Follow the branch name convention as described in [CONTRIBUTING.md](github.com/jmprathab/MyHome/blob/master/CONTRIBUTING.md)

This PR is ready to be merged after done.

2020-10-15 03:14 UTC, tomsajuk commented
Closing this PR as requires branch name change. Please check PR #197

2020-10-15 03:14 UTC, closed without merging