Issue #173: Convert /members/{memberId}/documents to OpenApi yaml spe…
jmprathab/MyHome pull request #188
Opened 2020-10-11 15:48 UTC by huyle1097

## 🚀 Description
Added OpenAPI spec for HouseMemberDocumentController

## 📄 Motivation and Context
Fixes Issue #173 

## 🧪 How Has This Been Tested?

- Test cases are passing

- Verified functionalities via running locally Home-Web UI

## 📷 Screenshots (if appropriate)

## 📦 Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [x] My code follows the code style of this project(Do your best to follow code styles. If none apply just skip this).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-10-11 17:17 UTC, mslowiak requested changes
There are small changes so it should not take long to fix that.
However please use rebase rather than merge, thanks :)

2020-10-11 17:17 UTC, mslowiak commented on api/src/main/resources/api.yaml
> +        - HouseMemberDocuments
Let's change the tag name to `Documents` and list it in tags names in line 9

2020-10-11 17:17 UTC, mslowiak commented on api/src/main/resources/api.yaml
> +          description: id document deleted
`id` -> `if`

2020-10-11 17:17 UTC, mslowiak commented on api/src/main/resources/api.yaml
> +          description: If document updated
`If`  -> `if` to be consistent

2020-10-11 17:17 UTC, mslowiak commented on api/src/main/resources/api.yaml
> +          description: If document saved
`If`  -> `if` to be consistent

2020-10-12 01:18 UTC, huyle1097 commented
> However please use rebase rather than merge, thanks :)

Hey @mslowiak 
Do I need to revert the merge commit then do the rebase?
After I commit the new changes, I try to rebase with _upstream/master_ but it looks so worst :disappointed: 
![image](https://user-images.githubusercontent.com/23402717/95695949-60303600-0c63-11eb-9098-cf67688a7203.png)
Sorry, I never use rebase before :crying_cat_face:

2020-10-12 10:28 UTC, mslowiak approved these changes

2020-10-12 10:29 UTC, mslowiak commented
Thank you for your contribution @huyle1097 :)

2020-10-12 10:29 UTC, merged

2020-10-12 10:34 UTC, mslowiak commented
@huyle1097 
For the future issues please include 'Closes: #173' instead of 'Fixes Issue #173'. That will automatically close issue when PR is merged :)

2020-10-12 12:00 UTC, huyle1097 commented
Thanks @mslowiak