Feature/issue 176  Added OpenAPI spec for AmenityController
jmprathab/MyHome pull request #195
Opened 2020-10-13 21:38 UTC by SergeyHydra

🚀 Description

Added OpenAPI spec for AmenityController

📄 Motivation and Context

Fixes Issue #176 

🧪 How Has This Been Tested?

Test cases are passing
Endpoints are working
📷 Screenshots (if appropriate)

📦 Types of changes

  Bug fix (non-breaking change which fixes an issue)
  New feature (non-breaking change which adds functionality)
  Breaking change (fix or feature that would cause existing functionality to not work as expected)
✅ Checklist

  My code follows the code style of this project(Do your best to follow code styles. If none apply just skip this).
  My change requires a change to the documentation.
  I have updated the documentation accordingly.

2020-10-13 22:21 UTC, mslowiak requested changes
The build is failing because of non implemented methods in CommunityController

2020-10-13 22:21 UTC, mslowiak commented on service/src/main/java/com/myhome/controllers/AmenityController.java
> +public class AmenityController implements AmenitiesApi, CommunitiesApi {
`AmenityController ` should only implement `AmenitiesApi`

2020-10-13 22:21 UTC, mslowiak commented on api/src/main/resources/api.yaml
> +        - Amentities
`Amentities` tag is not added in line 11 of this file

2020-10-13 22:21 UTC, mslowiak commented on api/src/main/resources/api.yaml
> +          type: long
long is incorrect in OpenApi specification, please use:
```
type: integer
format: int64
```

2020-10-13 22:21 UTC, mslowiak commented
Please use rebase over merge and fix the pull request name

2020-10-14 20:19 UTC, SergeyHydra commented
@mslowiak can I move methods with community path from AmenityController to CommunityController?

2020-10-18 17:44 UTC, mslowiak requested changes
Looks good for me but please use rebase over merge. 
Ping me when it will be fixed so we can merge it

2020-10-21 16:34 UTC, mslowiak commented
@SergeyHydra 
Looks like the build is failing

2020-10-29 02:24 UTC, jmprathab commented
@SergeyHydra Please fix the build and resolve the conflicts. Once done this is ready to merge.

2020-11-03 07:44 UTC, mslowiak approved these changes

2020-11-05 14:25 UTC, merged