Issue 199 Sending valid error messages from backend during sign in/ signup to the forntend
jmprathab/MyHome pull request #201
Opened 2020-10-23 13:45 UTC by piotrkosinski1992

## 🚀 Description
https://github.com/jmprathab/MyHome/issues/199
Sorry for formatting on generated mapstruct files

📄 Motivation and Context
Fixes Issue #199

2020-10-29 02:25 UTC, jmprathab commented
@piotrkosinski1992 Can you please resolve the conflicts?

2020-10-31 20:14 UTC, mslowiak requested changes
- There are some changes needed described in comments
- Rebase is needed to resolve conflicts
- Please name PR and commit messages as described in CONTRIBUTTING.MD

2020-10-31 20:14 UTC, mslowiak commented on api/src/main/resources/api.yaml
> -          content:
+1

2020-10-31 20:14 UTC, mslowiak commented on service/src/main/generated/com/myhome/controllers/dto/mapper/CommunityMapperImpl.java
> +@Generated(
Why we have those mappers in `service/src/main/generated`?
They were under `service/build/generated` and not tracked by git

2020-10-31 20:14 UTC, mslowiak commented on service/src/main/java/com/myhome/controllers/ApiErrorHandler.java
> +@ControllerAdvice
How about `RestControllerAdvice`? 
https://stackoverflow.com/a/43124517/5785871

2020-10-31 20:14 UTC, mslowiak commented on service/src/test/java/com/myhome/services/unit/UserSDJpaServiceTest.java
> +    verify(userRepository).save(User.builder()
formatting

2020-10-31 20:14 UTC, mslowiak commented on service/src/test/java/com/myhome/services/unit/UserSDJpaServiceTest.java
> +    Exception exception = Assertions.assertThrows(
Let's use static import for `assertThrows`

2020-10-31 20:14 UTC, mslowiak commented on service/src/test/java/com/myhome/services/unit/UserSDJpaServiceTest.java
> +        () -> userService.createUser(request));
Let's move `);` to the new line

2020-10-31 20:14 UTC, mslowiak commented on service/src/test/java/com/myhome/services/unit/UserSDJpaServiceTest.java
> +    Exception exception = Assertions.assertThrows(
Let's use static import

2020-10-31 20:14 UTC, mslowiak commented on service/src/main/java/com/myhome/services/springdatajpa/UserSDJpaService.java
> +    verifyEmailUniqueness(dto);
Let's wrap it in optional and use filter/orElse rather than putting that in void methods

2020-10-31 20:14 UTC, mslowiak commented on service/src/main/java/com/myhome/services/springdatajpa/UserSDJpaService.java
> +  private void saveUser(UserDto request) {
Let's return the `UserDto` from this method and also from the service.
Just ignore it in `UserController`.

That would:
- be easier to tests
- will not have magic logic inside void methods
- will be more functional approach

2020-10-31 20:14 UTC, mslowiak commented on service/src/main/java/com/myhome/controllers/ApiErrorHandler.java
> +  @ExceptionHandler(value = { Exception.class })
Let's pass here all the exceptions that we throw in application and create handleException method per each HTTP code that we want to return - we will do not have to manage the http codes in exception descriptions.

Non handled exceptions should be handled as INTERNAL_SERVER_ERROR (500 code)

2021-02-18 16:20 UTC, mslowiak commented
Closing - no feedback from contributor

2021-02-18 16:20 UTC, closed without merging