Feature #46 CAPTURE_DURATION_OF_STAY
jmprathab/MyHome pull request #202
Opened 2020-10-23 18:35 UTC by Giluerre

## 🚀 Description
**Feature adds** 

- HouseHistory entity

- Two new Endpoints:
 **POST:  /houses/member/captureStay**
    add stay of duration 

 **GET /houses/{houseId}/houseHistory**
   find all records where houseId is same, Query param memberId is optional.

- New methods in Housecontroller are migrated to openAPI

## 📄 Motivation and Context

## 🧪 How Has This Been Tested?
Feature was tested by sending requests via Postman.

## 📷 Screenshots (if appropriate)

## 📦 Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [ ] My code follows the code style of this project(Do your best to follow code styles. If none apply just skip this).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-11-02 03:28 UTC, jmprathab commented
@Giluerre Can you please refactor it to use the new endpoints as described in https://github.com/jmprathab/MyHome/issues/46#issue-659905122?

Current implementation is not so RESTFul.

2020-11-02 03:29 UTC, jmprathab requested changes
Please make the changes as per the newly updated issue description.

2020-11-06 22:48 UTC, Giluerre commented
@jmprathab Yes, I can. I apologize for the inactivity.

2021-02-18 19:59 UTC, mslowiak requested changes
The whole code needs the correct formatting.
There are many comments, please read them and feel free to raise a new PR with proper code, thanks!

2021-02-18 19:59 UTC, mslowiak commented on api/src/main/resources/api.yaml
> +        - house-controller
`Rentals`

2021-02-18 19:59 UTC, mslowiak commented on api/src/main/resources/api.yaml
> +      operationId: captureStay
Can this method be more meaningful?

2021-02-18 19:59 UTC, mslowiak commented on api/src/main/resources/api.yaml
> +        - house-controller
`Rentals`

2021-02-18 19:59 UTC, mslowiak commented on api/src/main/resources/api.yaml
> +      operationId: getHouseHistory
`getHouseHistory`?
Maybe it would be better to name it like `getRentalHistoryForHouse`?

2021-02-18 19:59 UTC, mslowiak commented on api/src/main/resources/api.yaml
> +          description: "if history is present"
Quotes can be omitted. Start the sentence with uppercase

2021-02-18 19:59 UTC, mslowiak commented on api/src/main/resources/api.yaml
> +          description: "if params are invalid"
Quotes can be omitted. Start the sentence with uppercase

2021-02-18 19:59 UTC, mslowiak commented on api/src/main/resources/api.yaml
> +        histories:
`histories` - is this name appropriate?
How about `houseRentalHistory`, `rentalHistory`?

2021-02-18 19:59 UTC, mslowiak commented on api/src/main/resources/api.yaml
> +    HouseHistoryResponse:
Is this the same as `HouseHistoryDto`?

2021-02-18 19:59 UTC, mslowiak commented on service/src/main/java/com/myhome/controllers/HouseController.java
> +    if (!houseService.getHouseHistory(memberId,houseId).isPresent()) {
Please do not use `isPresent` if not really needed.
You can work with `.map` operator

2021-02-18 19:59 UTC, mslowiak commented on service/src/main/java/com/myhome/controllers/HouseController.java
> +    return ResponseEntity.status(HttpStatus.OK).body(listHouseHistoryResponse);
`ResponseEntity.status(HttpStatus.OK).body(listHouseHistoryResponse)`

can be simplified to:
`ResponseEntity.ok(listHouseHistoryResponse)`

2021-02-18 19:59 UTC, mslowiak commented on service/src/main/java/com/myhome/controllers/dto/mapper/HouseHistoryMapper.java
> +  HouseHistoryResponse HouseHistoryDtoToHouseHistoryResponse(HouseHistoryDto houseHistoryDto);
Why all the methods starts with uppercase?

2021-02-18 19:59 UTC, mslowiak commented on service/src/main/java/com/myhome/controllers/HouseController.java
> +            .HouseHistoryToHouseHistoryDto(houseService
Maybe some part of this can be extracted to a variable?

2021-02-18 19:59 UTC, mslowiak commented on service/src/main/java/com/myhome/controllers/HouseController.java
> +        : ResponseEntity.status(HttpStatus.BAD_REQUEST).body(houseHistoryResponse));
Do we really want to return there a 400 response? Why?

2021-02-18 19:59 UTC, mslowiak commented on service/src/main/java/com/myhome/domain/HouseHistory.java
> +
blank lines

2021-02-18 19:59 UTC, mslowiak commented on service/src/main/java/com/myhome/repositories/HouseHistoryRepository.java
> +  List<HouseHistory> findByHouseId(String houseId);
Please take a look at FIND vs GET naming convention:

https://softwareengineering.stackexchange.com/questions/182113/how-and-why-to-decide-between-naming-methods-with-get-and-find-prefixes/182120

2021-02-18 19:59 UTC, mslowiak commented on service/src/main/resources/data.sql
> +
not needed I guess

2021-02-18 19:59 UTC, mslowiak commented on service/src/main/java/com/myhome/services/springdatajpa/HouseSDJpaService.java
> +  @Override public Optional<List<HouseHistory>> getHouseHistory(String memberId, String houseId) {
Put override in new line, please.

2021-02-18 19:59 UTC, mslowiak commented on service/src/test/java/helpers/TestUtils.java
> +import javax.rmi.CORBA.Util;
Why this import is there?

2021-02-18 19:59 UTC, mslowiak commented
Closing - too many code issues. 
Feel free to raise a new PR with fixed code @Giluerre.

2021-02-18 19:59 UTC, closed without merging