Issue #206: PaymentController can only respond with 404 or with NullPointerException when creating Payment
jmprathab/MyHome pull request #210
Opened 2020-12-08 21:05 UTC by edwardUL99

I didn't realise I had to name the commit with the specified pattern, sorry!

## 🚀 Description

This PR closes #206.

It has the following changes:

- An AfterMapping method has been added to SchedulePaymentApiMapper so that after mapping a payment request to an enriched one, it fills in the null admin and member which were causing the NullPointerExceptions.
- A ManyToOne relationship also had to be added to admin and member in Payment.java, as without them, there were issues with fields being too long
- Payment#description was defined as unique but this was causing issues after fixing the other issue. It makes sense that a description should not be unique

## 📄 Motivation and Context

This big fix resolves the NullPointerExceptions blocking pull request #205. It closes #206 

## 🧪 How Has This Been Tested?

Since pull request #205 has not been merged yet, I copied all the required code over to my branch to re-run the failing test. I removed the Disabled annotation and ran the test and it passed.

Also used Postman to test the scenario of creating a payment. I tried the scenario of creating a payment with an admin ID that is not in the community of the member ID and got the 404 response because it couldn't find that admin in the member's community.

## 📷 Screenshots (if appropriate)

## 📦 Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [X] My code follows the code style of this project(Do your best to follow code styles. If none apply just skip this).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-02-17 15:57 UTC, mslowiak commented
`A ManyToOne relationship also had to be added to admin and member in Payment.java, as without them, there were issues with fields being too long`

@edwardUL99 Can you elaborate on that? What means 'fields being too long' ? 
BTW. Sorry for the late response on that

2021-02-17 22:47 UTC, edwardUL99 commented
> > A ManyToOne relationship also had to be added to admin and member in Payment.java, as without them, there were issues with fields being too long
> 
> @edwardUL99 
> Can you elaborate on that? What means 'fields being too long'? 
> BTW. Sorry for the late response on that

I don't really remember now, in hindsight should have documted the stack trace. I believe it was an exception with IDs being greater than 255 characters. Some reason adding ManyToOne fixed that, I'm not too sure.

2021-02-20 11:40 UTC, mslowiak requested changes
There are small changes but if you correct them we can merge that @edwardUL99

2021-02-20 11:40 UTC, mslowiak commented on service/src/main/java/com/myhome/domain/Payment.java
> -  @Column(unique = true, nullable = false)
nice catch!

2021-02-20 11:40 UTC, mslowiak commented on service/src/main/java/com/myhome/controllers/mapper/SchedulePaymentApiMapper.java
> +    return UserDto.builder().userId(enrichedSchedulePaymentRequest.getAdminId())
Could you move `userId` to the next line?

2021-02-20 11:40 UTC, mslowiak commented on service/src/main/java/com/myhome/controllers/mapper/SchedulePaymentApiMapper.java
> +    return new HouseMemberDto().id(enrichedSchedulePaymentRequest.getMemberEntityId())
Could you move `id` to the next line?

2021-02-20 21:35 UTC, merged

2021-02-20 21:36 UTC, mslowiak commented
Thanks @edwardUL99

2021-02-20 21:39 UTC, edwardUL99 commented
@mslowiak The changes are done but got a codecov error. I tried rebasing but it said my branch diverged by 33 and 2 commits respectively between local and remote branch. I believe it is because the branch has already been pushed

2021-02-20 21:40 UTC, edwardUL99 commented
No problem @mslowiak

2021-02-20 22:01 UTC, mslowiak commented
Feel free to take something new, there are plenty of new issues @edwardUL99 ! :)