Issue #243: add unit tests for AuthenticationController, AuthenticationSDJpaService, UserSDJpaService (method findUserByEmail)
jmprathab/MyHome pull request #251
Opened 2021-03-01 13:12 UTC by hsergiu

## 🚀 Description
Created multiple tests for each method. Only a single one for login() in AuthenticationController.

## 📄 Motivation and Context

Solves #243 

## 📦 Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [x] My code follows the code style of this project(Do your best to follow code styles. If none apply just skip this).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-03-02 20:51 UTC, mslowiak requested changes
@hsergiu 
Thank you for your contribution.
There are few changes that I mentioned in the comments. Please reformat also all classes that were touched by you (I saw some code snippets that had no space after brackets etc).

2021-03-02 20:51 UTC, mslowiak commented on service/src/test/java/com/myhome/services/unit/UserSDJpaServiceTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Wildcards imports.
Why is it bad? Read it here https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad

How you can fix it in intellij?
https://stackoverflow.com/a/25916603/5785871

2021-03-02 20:51 UTC, mslowiak commented on service/src/test/java/com/myhome/services/unit/AuthenticationSDJpaServiceTest.java
> +    Assertions.assertThrows(UserNotFoundException.class, () -> authenticationSDJpaService.login(request));
Could you use static import for `assertThrows`?

2021-03-02 20:51 UTC, mslowiak commented on service/src/test/java/com/myhome/services/unit/AuthenticationSDJpaServiceTest.java
> +    Assertions.assertThrows(CredentialsIncorrectException.class, () -> authenticationSDJpaService.login(request));
Same as above - static import please

2021-03-02 20:51 UTC, mslowiak commented on service/src/test/java/com/myhome/services/unit/AuthenticationSDJpaServiceTest.java
> +    LoginRequest request = new LoginRequest();
Generated classes (in this case `LoginRequest`) have something similar to builder pattern.
You can write `LoginRequest.email(USER_EMAIL).password(REQUEST_PASSWORD)`

2021-03-02 20:51 UTC, mslowiak commented on service/src/test/java/com/myhome/services/unit/AuthenticationSDJpaServiceTest.java
> +    ReflectionTestUtils.setField(authenticationSDJpaService, "tokenExpirationTime", Duration.ofDays(1));
Using reflection is a bad practice.
We can make `AllArgsConstructor` annotation above `AuthenticationSDJpaService` or create all args constructor by hand and use there the annotations:
```
public AuthenticationSDJpaService(@Value("${token.expiration_time}") Duration tokenExpirationTime,
                                    @Value("${token.secret}") String tokenSecret,
                                    UserSDJpaService userSDJpaService,
                                    AppJwtEncoderDecoder appJwtEncoderDecoder,
                                    PasswordEncoder passwordEncoder) {
    this.tokenExpirationTime = tokenExpirationTime;
    this.tokenSecret = tokenSecret;
    this.userSDJpaService = userSDJpaService;
    this.appJwtEncoderDecoder = appJwtEncoderDecoder;
    this.passwordEncoder = passwordEncoder;
  }
```

That will give you a way to not inject properties with reflection :)

2021-03-02 20:51 UTC, mslowiak commented on service/src/test/java/com/myhome/controllers/AuthenticationControllerTest.java
> +        assertEquals(response.getHeaders().size(), 2);
Can we expand this assertion to check not just the size of headers but if there are proper headers with appropriate values (propagated from mocked authentication service)?

2021-03-02 20:51 UTC, mslowiak commented on service/src/test/java/com/myhome/controllers/AuthenticationControllerTest.java
> +/*
That copyright can be deleted :D

2021-03-03 20:06 UTC, mslowiak commented on service/src/main/java/com/myhome/services/springdatajpa/AuthenticationSDJpaService.java
>    @Value("${token.expiration_time}")
If you added the `@Value` annotation in the constructor, then it doesn't need to be on the variable definition as well.

2021-03-03 20:08 UTC, mslowiak commented
@hsergiu Just one more comment about this PR and we can proceed with merge :)

2021-03-03 20:55 UTC, hsergiu commented
Thank you for the review. I made the changes.

2021-03-03 21:01 UTC, mslowiak approved these changes

2021-03-03 21:01 UTC, merged