Feature/257  delete amenity cases error 500
jmprathab/MyHome pull request #258
Opened 2021-03-09 22:54 UTC by DDmit04

## 🚀 Description

fix 500 error on delete amenity

## 📄 Motivation and Context

Do we need both of this fields in `Amenity`?
```
@ManyToOne(fetch = FetchType.LAZY)
private Community community;
@ManyToOne(fetch = FetchType.LAZY)
private CommunityHouse communityHouse;
```

May be stay only `communityHouse`? 
All `Amenity` entities `communityHouse`  field is NULL because we need fix `data.sql`
In postman collection 'GET /communities/{communityId}/amenities' is not present (i think i'll fix this solving #113)

## 🧪 How Has This Been Tested?

## 📷 Screenshots (if appropriate)

## 📦 Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2021-03-10 16:43 UTC, mslowiak commented
Could you rename the PR name and resolve conflicts @DDmit04 ?

2021-03-11 18:27 UTC, mslowiak approved these changes

2021-03-11 18:27 UTC, mslowiak commented on service/src/main/java/com/myhome/controllers/CommunityController.java
> +  private final AmenityService amenitySDJpaService;
??

2021-03-11 18:27 UTC, mslowiak commented on service/src/main/java/com/myhome/controllers/CommunityController.java
> +  private final PaymentService paymentService;
??

2021-03-11 18:27 UTC, mslowiak commented on service/src/main/java/com/myhome/controllers/CommunityController.java
> +  private final AmenityApiMapper amenityApiMapper;
??

2021-03-11 18:27 UTC, mslowiak commented on service/src/main/java/com/myhome/controllers/CommunityController.java
> +  private final SchedulePaymentApiMapper schedulePaymentApiMapper;
??

2021-03-11 18:27 UTC, mslowiak commented on service/src/test/java/com/myhome/services/unit/AmenityBookingSDJpaServiceTest.java
> +  private static final String TEST_BOOKING_ID = "test-booking-id";
let's add blank line here

2021-03-11 18:27 UTC, mslowiak commented on service/src/test/java/com/myhome/services/unit/AmenityBookingSDJpaServiceTest.java
> +  void deleteBookingItem() {
rename to `shouldDeleteBookingItem`

2021-03-11 18:27 UTC, mslowiak commented on service/src/test/java/com/myhome/services/unit/AmenityBookingSDJpaServiceTest.java
> +  void deleteBookingNotExists() {
rename to `shouldNotDeleteBookingItemIfNotExists`

2021-03-11 18:27 UTC, mslowiak commented on service/src/test/java/com/myhome/services/unit/CommunitySDJpaServiceTest.java
> +  void listAllAmenities() {
rename `shouldListAllAmenities`

2021-03-11 18:27 UTC, mslowiak commented on service/src/test/java/com/myhome/services/unit/CommunitySDJpaServiceTest.java
> +  void listAllAmenitiesNotExists() {
rename `shouldReturnZeroResultsIfNoAmenitiesPresent`

2021-03-12 07:29 UTC, mslowiak requested changes
Please squash changes beetween `603ad2a86f11a90f86dea1680775b6fdd97fd2a4` and `1c76c92b81ff1b2549b24b20d2c3d685c7ab1581` because the history of codebase is modified by this adding and deleting fields but it should not...
It is related to problematic rebase/merge with master on your side

2021-03-21 17:24 UTC, aidanBurton commented on service/src/test/java/com/myhome/services/unit/AmenityBookingSDJpaServiceTest.java
> +  void ShouldNotRemoveAllAmenityBookingsIfAmenityNotExists() {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

2021-04-10 13:13 UTC, DDmit04 commented
@mslowiak This can be merged?

2024-01-12 12:17 UTC, closed without merging