Issue#47 ability to add documents for a house member
jmprathab/MyHome pull request #75
Opened 2020-07-29 00:40 UTC by DDmit04

## 🚀 Description

Create CRUD endpoints for house member documents

### New classes:

* `FileUploadConfig` - class for configure max file size for uploading to server
* `HouseMemberDocument` - a new entity that represents house member document
* `HouseMemberDocumentService` (and implementation - HouseMemberDocumentSDJpaService) - service for HouseMemberDocument 
* `HouseMemberDocumentController` - controller for HouseMemberDocument 
* `FileUploadExceptionAdvice` - class for handle excaptions from controller and return error codes

### Important:

* Document image data stored in database. I think this is right because this data needs more secure and image size isn't very large
* The final image size after compression cannot be calculated (for example: 400KB image with 50% quality applied, not always 200KB image in result)

### Problems:

* `HouseMemberDocument` field in `HouseMember` always use FetchTYpe.EAGER because bidirectional OneToOne relationship ignores FetchTYpe.LAZY
* GET `/members/{memberId}/documents` returns `404` in 2 cases: when invalid memberId and when house member document is empty - this can be confusing.

## 📄 Motivation and Context

solving #47 

## 📦 Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2020-07-29 07:02 UTC, mslowiak requested changes

2020-07-29 07:02 UTC, mslowiak commented on src/main/java/com/myhome/controllers/HouseMemberDocumentController.java
> +        if(houseMemberDocumentOptional.isPresent()) {
Use Optional.of(<something>).map(<isPresentLogic).orElseGet(<else logic>)

2020-07-29 07:02 UTC, mslowiak commented on src/main/java/com/myhome/domain/HouseMember.java
> +import javax.persistence.*;
Wildcard import.
https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad
https://rules.sonarsource.com/java/RSPEC-2208

2020-07-29 07:02 UTC, mslowiak commented on src/main/java/com/myhome/domain/HouseMemberDocument.java
> +import javax.persistence.*;
Wildcard import.
https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad
https://rules.sonarsource.com/java/RSPEC-2208

2020-07-29 07:02 UTC, mslowiak commented on src/main/java/com/myhome/repositories/HouseMemberDocumentRepository.java
> +public interface HouseMemberDocumentRepository extends CrudRepository<HouseMemberDocument, Long> {
Let's use `JpaRepository` or at least `PagingAndSorting` repository since we need a support for that.

2020-07-29 07:02 UTC, mslowiak commented on src/main/java/com/myhome/services/springdatajpa/HouseMemberDocumentSDJpaService.java
> +import java.io.*;
wildcard import

2020-07-29 07:02 UTC, mslowiak commented on src/main/java/com/myhome/services/springdatajpa/HouseMemberDocumentSDJpaService.java
> +    public HouseMemberDocumentSDJpaService(HouseMemberRepository houseMemberRepository, HouseMemberDocumentRepository houseMemberDocumentRepository) {
Can be replaced with `@RequiredArgsConstructor` annotation on class level

2020-07-29 07:02 UTC, mslowiak commented on src/main/java/com/myhome/services/springdatajpa/HouseMemberDocumentSDJpaService.java
> +        HouseMember member = houseMemberRepository.findByMemberId(memberId);
```
return houseMemberRepository.findByMemberId(memberId)
            .map(member -> member.getHouseMemberDocument())
```

2020-07-29 07:02 UTC, mslowiak commented on src/main/java/com/myhome/services/springdatajpa/HouseMemberDocumentSDJpaService.java
> +        HouseMember member = houseMemberRepository.findByMemberId(memberId);
Let's use optionals basing on previous examples in code review

2020-07-29 07:02 UTC, mslowiak commented on src/main/java/com/myhome/services/springdatajpa/HouseMemberDocumentSDJpaService.java
> +        memberDocumentFile.delete();
delete?

2020-07-29 07:02 UTC, mslowiak commented on src/main/java/com/myhome/services/springdatajpa/HouseMemberDocumentSDJpaService.java
> +        return createHouseMemberDocument(multipartFile, memberId);
It is misleading. New document is created

2020-07-29 07:02 UTC, mslowiak commented on src/main/java/com/myhome/services/springdatajpa/HouseMemberDocumentSDJpaService.java
> +        if (multipartFile.getSize() < 1024 * compressionBorderSizeKBytes) {
Magic number: 1024

https://stackoverflow.com/questions/47882/what-is-a-magic-number-and-why-is-it-bad

2020-07-29 07:02 UTC, mslowiak commented on src/main/java/com/myhome/services/springdatajpa/HouseMemberDocumentSDJpaService.java
> +        newDocument.setDocument(Files.readAllBytes(documentFile.toPath()));
Constructor can be used instead of setters since you assign all fields from `HouseMemberDocument `

2020-07-29 15:05 UTC, jmprathab commented on src/main/resources/application.yml
> +  files:
Can this be moved to "Custom properties" section?

2020-07-29 15:12 UTC, jmprathab commented on src/main/java/com/myhome/repositories/HouseMemberDocumentRepository.java
> +public interface HouseMemberDocumentRepository extends CrudRepository<HouseMemberDocument, Long> {
+1 for the suggestion. But, just curious about which API within this context needs paging and sorting functionality.

2020-07-29 19:18 UTC, mslowiak commented on src/main/java/com/myhome/repositories/HouseMemberDocumentRepository.java
> +public interface HouseMemberDocumentRepository extends CrudRepository<HouseMemberDocument, Long> {
Are we considering only one document per user or more?

2020-07-29 21:49 UTC, DDmit04 commented on src/main/java/com/myhome/services/springdatajpa/HouseMemberDocumentSDJpaService.java
> +        memberDocumentFile.delete();
For compress image I create new file (it apears in app running detectory) then I write compressed image to this file and save file in badabase as byte[] but created file steel exists in file system so it must be deleted.

2020-07-31 05:09 UTC, jmprathab commented
@DDmit04 can you please take care of the review comments by @mslowiak ?
Please mark the conversation as resolved once you have made the required changes.

2020-07-31 06:55 UTC, mslowiak commented on src/main/java/com/myhome/services/springdatajpa/HouseMemberDocumentSDJpaService.java
> +        memberDocumentFile.delete();
IS it necessary to create a new file? Can't compression by done on the fly on `byte[]` array?

2020-07-31 11:51 UTC, DDmit04 commented on src/main/java/com/myhome/services/springdatajpa/HouseMemberDocumentSDJpaService.java
> +        memberDocumentFile.delete();
I will look for such a solution

2020-07-31 13:08 UTC, mslowiak commented
I think we can merge this PR but we should check if there is possibility to compress image on the fly according to [this](https://github.com/jmprathab/MyHome/pull/75#discussion_r462080482). We should have another issue to track that if so.

2020-07-31 13:09 UTC, mslowiak approved these changes

2020-07-31 13:33 UTC, DDmit04 commented on src/main/java/com/myhome/services/springdatajpa/HouseMemberDocumentSDJpaService.java
> +        memberDocumentFile.delete();
OK I found solution. I use `ByteArrayOutputStream` insead `File` and `FileOutputStream`

2020-07-31 13:47 UTC, DDmit04 commented
I can't uderstand why build failing

2020-07-31 14:28 UTC, DDmit04 commented
There is two problems left:
* POST an UPDATE (`/members/{memberId}/documents`) in controller do the same thing and I don't know what to do with this
* I can't create unit test for POST and UPDATE because they needs up `applicationContext` to extract varibles from application.yaml. I can use anotation `@SpringBootTest` but in this case test run times are getting too long. May be I should create separate test class for POST and UPDATE

2020-07-31 14:58 UTC, jmprathab commented
> There is two problems left:
> 
> * POST an UPDATE (`/members/{memberId}/documents`) in controller (and service) do the same thing and I don't know what to do with this
> * I can't create unit test for POST and UPDATE because they needs up `applicationContext` to extract varibles from application.yaml. I can use anotation `@SpringBootTest` but in this case test run times are getting too long. May be I should create separate test class for POST and UPDATE to run long tests separately from the rest

Please create tracking feature/bug request for this. We can take this up in the future.

2020-07-31 14:58 UTC, merged